### ISSUE TITLE
Broken pages.

### ISSUE THREAD

**Issue by marocchino** [ruby/www.ruby-lang.org#1069] opened 2015-05-05 03:05 UTC
I found broken page in Korean translation.
- https://www.ruby-lang.org/ko/documentation/installation/

![screen shot 2015-05-05 at 11 59 12 am](https://cloud.githubusercontent.com/assets/128431/7466448/15e2c126-f31e-11e4-9183-a6c4d6147306.png)

and Japanese page also ended middle of document.

- https://www.ruby-lang.org/ja/documentation/installation/

I did not check all of them, but many langs have same problem except en.

**Comment by marocchino** [comment] 2015-05-05 03:06
@hsbt @JuanitoFatas Can you fix this?

**Comment by namsk** [comment] 2015-05-07 04:48
:+1:

**Comment by spk** [comment] 2015-05-17 18:42
If fact the problem is for every languages.
If you `curl` a page the content is not complete, it cut generally around google-analytics script.
The problem is not reproducible with a local jekyll.

**Comment by stomar** [comment] 2015-05-25 16:30
Also, sometimes the delivered html files are truncated in the middle of the main body.

A quick test showed that the cut off is not at a specific file size.

**Comment by stomar** [comment] 2015-05-25 16:31
@hsbt Note this does not happen for a local jekyll build.

**Comment by stomar** [comment] 2015-05-26 10:14
The problem should be fixed, for now. Please report if not.

**Closed by stomar** 2015-05-26 10:14 UTC

**Comment by JuanitoFatas** [comment] 2015-05-26 11:47
:clap: :clap: :clap: :clap:
